const items = [
    {
        id: '001',
        image: 'images/Bar2.jpg',
        company: 'Nike',
        item_name: 'FC Barcelona Home 2008-09 Retro Messi Jersey',
        original_price: 2999,
        current_price: 1649,
        discount_percentage: 45,
        return_period: 14,
        delivery_date: '5 Nov 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/ManU.jpg',
        company: 'Nike',
        item_name: 'Manchester United Home 2008 Retro Ronaldo Jersey',
        original_price: 2999,
        current_price: 1699,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '6 Nov 2023',
        rating: {
            stars: 4.4,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/18.jpg',
        company: 'Cricket',
        item_name: 'Virat kohli 18',
        original_price: 2999,
        current_price: 1699,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '6 Nov 2023',
        rating: {
            stars: 4.4,
            count: 390,
        },

    },
    
    {
        id: '004',
        image: 'images/Bar3.jpg',
        company: 'Nike',
        item_name: 'FC Barcelona Home Kit 2023-24',
        original_price: 1899,
        current_price: 999,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/indian.avif',
        company: 'Adidas',
        item_name: 'India Official ODI Adidas Mens Shirt',
        original_price: 2999,
        current_price: 1899,
        discount_percentage: 37,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/indian2.avif',
        company: 'Fanatics',
        item_name: 'India Cricket World Cup Team Graphic Hoodie',
        original_price: 6999,
        current_price: 3999,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 10,
        },
    },
   
    {
        id: '007',
        image: 'images/Barcelona-away.webp',
        company: 'Puma',
        item_name: 'Virat kohli 18 IPL jersey',
        original_price: 2599,
        current_price: 1299,
        discount_percentage: 50,
        rating: {
            stars: 4.4,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/psg.jpg',
        company: 'Nike',
        item_name: 'PSG Jordan Fourth Kit 2022-23',
        original_price: 1899,
        current_price: 899,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 90,
        },
    },
    {
        id: '009',
        image: 'images/viratRCB.jpg',
        company: 'Nike',
        item_name: 'FC Barcelona Away Jersey 2020-21',
        original_price: 2599,
        current_price: 1599,
        discount_percentage: 40,
        return_period: 14,
        delivery_date: '4 Nov 2023',
        rating: {
            stars: 4.2,
            count: 249,
        },
    },

    {
        id: '010',
        image: 'images/custom4.jpeg',
        company: 'Fanatics',
        item_name: 'India Cricket World Cup Team Graphic Hoodie',
        original_price: 6999,
        current_price: 3999,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 10,
        },
    },
   
    {
        id: '011',
        image: 'images/custom5.png',
        company: 'Puma',
        item_name: 'Virat kohli 18 IPL jersey',
        original_price: 2599,
        current_price: 1299,
        discount_percentage: 50,
        rating: {
            stars: 4.4,
            count: 388,
        },
    },
    {
        id: '012',
        image: 'images/custom6.jpg',
        company: 'Puma',
        item_name: 'Virat kohli 18 IPL jersey',
        original_price: 2599,
        current_price: 1299,
        discount_percentage: 50,
        rating: {
            stars: 4.4,
            count: 388,
        },
    },
    {
        id: '013',
        image: 'images/golden.webp',
        company: 'Adidas',
        item_name: 'Real Madrid Home kit',
        original_price: 2599,
        current_price: 1699,
        discount_percentage: 37,
        return_period: 14,
        delivery_date: '4 Nov 2023',
        rating: {
            stars: 4.2,
            count: 249,
        },
    },
    {
        id: '014',
        image: 'images/lakers.webp',
        company: 'Adidas',
        item_name: 'Real Madrid Home kit',
        original_price: 2599,
        current_price: 1699,
        discount_percentage: 37,
        return_period: 14,
        delivery_date: '4 Nov 2023',
        rating: {
            stars: 4.2,
            count: 249,
        },
    },
    {
        id: '015',
        image: 'images/lebron.webp',
        company: 'Adidas',
        item_name: 'Real Madrid Home kit',
        original_price: 2599,
        current_price: 1699,
        discount_percentage: 37,
        return_period: 14,
        delivery_date: '4 Nov 2023',
        rating: {
            stars: 4.2,
            count: 249,
        },
    },
    {
        id: '016',
        image: 'images/basket.webp',
        company: 'Adidas',
        item_name: 'Real Madrid Home kit',
        original_price: 2599,
        current_price: 1699,
        discount_percentage: 37,
        return_period: 14,
        delivery_date: '4 Nov 2023',
        rating: {
            stars: 4.2,
            count: 249,
        },
    },
];

const items2 = [

    {
        id: '001',
        image: 'images/custom1.jpg',
        company: 'Nike',
        item_name: 'FC Barcelona Home 2008-09 Retro Messi Jersey',
        original_price: 1999,
        current_price: 1249,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '5 Nov 2023',
        rating: {
            stars: 4.5,
            count: 400,
        },
    },
    {
        id: '002',
        image: 'images/custom2.jpg',
        company: 'Nike',
        item_name: 'ENT sports jersey',
        original_price: 1899,
        current_price: 999,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '003',
        image: 'images/custom8.jpg',
        company: 'Adidas',
        item_name: 'India Official ODI Adidas Mens Shirt',
        original_price: 2999,
        current_price: 1899,
        discount_percentage: 37,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 3500,
        },
    },
    {
        id: '004',
        image: 'images/custom4.jpeg',
        company: 'Fanatics',
        item_name: 'India Cricket World Cup Team Graphic Hoodie',
        original_price: 6999,
        current_price: 3999,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 10,
        },
    },
   
    {
        id: '005',
        image: 'images/custom5.png',
        company: 'Puma',
        item_name: 'Virat kohli 18 IPL jersey',
        original_price: 2599,
        current_price: 1299,
        discount_percentage: 50,
        rating: {
            stars: 4.4,
            count: 388,
        },
    },
    {
        id: '006',
        image: 'images/custom6.jpg',
        company: 'Puma',
        item_name: 'Virat kohli 18 IPL jersey',
        original_price: 2599,
        current_price: 1299,
        discount_percentage: 50,
        rating: {
            stars: 4.4,
            count: 388,
        },
    },
    {
        id: '007',
        image: 'images/custom7.webp',
        company: 'Puma',
        item_name: 'Virat kohli 18 IPL jersey',
        original_price: 2599,
        current_price: 1299,
        discount_percentage: 50,
        rating: {
            stars: 4.4,
            count: 388,
        },
    }
]